### ISSUE TITLE
React.propTypes deprecated

### ISSUE THREAD

**Issue by kylekatarnls** [Chion82/native-base-web#10]
Hi,

It seems React.propTypes is deprecated and the "prop-types" module should be used instead.
https://github.com/Chion82/native-base-web/blob/a22f6ac3380364a78bb2bd09a9c9ec271a95d382/Components/vendor/react-native-drawer/index.js#L1

It should be replaced in each component to be compatible with last react version. If you wish, I can propose you a pull-request.

Thanks,

**Comment by mauron85** [comment]
jscodeshift can transform to prop-types so React 16 can be used.

>Replaces React.PropTypes references with prop-types and adds the appropriate import or require statement. This codemod is intended for React 15.5+.

https://github.com/reactjs/react-codemod/#react-proptypes-to-prop-types
